2404: rename wrapper script, too...

diff --git a/bin/gpu-2404-wrapper b/bin/gpu-2404-wrapper
--- a/bin/gpu-2404-wrapper
+++ b/bin/gpu-2404-wrapper
@@ -1,16 +1,16 @@
 #!/bin/sh
 
-if ! snapctl is-connected graphics-core24
+if ! snapctl is-connected gpu-2404
 then
-  echo "ERROR: the graphics-core24 interface isn't connected."
+  echo "ERROR: the gpu-2404 interface isn't connected."
   echo "  Please install and connect a graphics userspace provider."
   echo ""
-  echo "The default provider is mesa-core24, you can install it and connect by issuing:"
-  echo "  sudo snap install mesa-core24"
-  echo "  sudo snap connect ${SNAP_INSTANCE_NAME}:graphics-core24 mesa-core24"
+  echo "The default provider is mesa-2404, you can install it and connect by issuing:"
+  echo "  sudo snap install mesa-2404"
+  echo "  sudo snap connect ${SNAP_INSTANCE_NAME}:gpu-2404 mesa-2404"
   echo ""
-  echo "See https://mir-server.io/docs/the-graphics-core24-snap-interface for more information."
+  echo "See https://mir-server.io/docs/the-gpu-2404-snap-interface for more information."
   exit 1
 fi
 
-exec "${SNAP}/graphics/bin/graphics-core24-provider-wrapper" "$@"
+exec "${SNAP}/graphics/bin/gpu-2404-provider-wrapper" "$@"
